config/routes.rb
CarLot::Application.routes.draw do
  resources :cars

end

app/models/car.rb
class Car < ActiveRecord::Base
  validates_presence_of :color
  validates_presence_of :year
  validates_presence_of :milage
  validates_numericality_of :year, greater_than_or_equal_to: 1980, less_than_or_equal_to: 2015
  validates_numericality_of :milage, greater_than_or_equal_to: 0
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_form.html.erb
<%= simple_form_for(@car) do |f| %>
  <%= f.input :color %>
  <%= f.input :year %>
  <%= f.input :milage %>
  <%= f.input :description %>
  <%= f.submit %>
<% end %>

app/views/cars/index.html.erb
<h1>Welcome!</h1>
<h2>Here are some cars, I guess!</h2>

<% @cars.each do |car| %>
  <p>Color: <%= car.color %></p>
  <p>Year: <%= car.year %></p>
  <p>Mileage: <%= car.milage %></p>
  <p>Description: <%= car.description %></p>
<% end %>
<br><hr>
<%= link_to 'Add a Car', new_car_path %>

app/views/cars/new.html.erb
<h1>Add a Car</h1>

<%= render 'cars/form', car: @car %>

app/views/cars/show.html.erb
<p><strong>Color:</strong> <%= @car.color %></p>
<p><strong>Year:</strong> <%= @car.year %></p>
<p><strong>Mileage:</strong> <%= @car.milage %></p>
<p><strong>Description:</strong> <%= @car.description %></p>

<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarLot</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>